package com.heyu.train.member.req;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import lombok.Data;

import java.util.Date;

/**
 * 乘车人（表：passenger）
 *
 * @author heyu
 * @date 2024-03-31 13:51:34
 */
@Data
public class PassengerReq {
    /**
     * id
     */
    private Long id;

    /**
     * 会员id
     */
    private Long memberId;

    /**
     * 姓名
     */
    @NotBlank(message = "姓名不能为空")
    private String name;

    /**
     * 身份证
     */
    @NotBlank(message = "身份证不能为空")
    @Pattern(regexp = "^[1-9]\\d{5}(18|19|([23]\\d))\\d{2}((0[1-9])|(10|11|12))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]$", message = "身份证号格式错误")
    private String idCard;

    /**
     * 旅客类型|枚举[PassengerTypeEnum]
     */
    @NotBlank(message = "旅客类型不能为空")
    private String type;

    /**
     * 新增时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.id
     *
     * @return the value of passenger.id
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.id
     *
     * @param id the value for passenger.id
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.member_id
     *
     * @return the value of passenger.member_id
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.member_id
     *
     * @param memberId the value for passenger.member_id
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.name
     *
     * @return the value of passenger.name
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.name
     *
     * @param name the value for passenger.name
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.id_card
     *
     * @return the value of passenger.id_card
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.id_card
     *
     * @param idCard the value for passenger.id_card
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.type
     *
     * @return the value of passenger.type
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.type
     *
     * @param type the value for passenger.type
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.create_time
     *
     * @return the value of passenger.create_time
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.create_time
     *
     * @param createTime the value for passenger.create_time
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.update_time
     *
     * @return the value of passenger.update_time
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.update_time
     *
     * @param updateTime the value for passenger.update_time
     * @mbg.generated Sun Mar 31 13:51:34 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}