server:
  port: 8001
  servlet:
    context-path: /member
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.heyu.train.member.mapper: trace

