server:
  port: 8001
  servlet:
    context-path: /member
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    type-aliases-package:  com.heyu.train.member.domain
logging:
  level:
    com.heyu.train.member.mapper: trace
#
#swagger:
#  enable: true
#  name: MAIYUN-FINANCE-ADMIN-API
#  description: MAIYUN-FINANCE-ADMIN-API 接口文档
#  version: 0.0.1
#
## Swagger UI
#knife4j:
#  enable: true
#  production: false
#  setting:
#    language: zh-CN
#    enableDynamicParameter: true