spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/member/**
        - id: business
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/business/**
        - id: batch
          uri: http://127.0.0.1:8007
          predicates:
            - Path=/batch/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            #            跨域请求的有效，会发送option请求
            maxAge: 3600
            allowCredentials: true
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: train

server:
  port: 10010

