server:
  port: 8002
  servlet:
    context-path: /business
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.heyu.train.business.domain
logging:
  level:
    com.heyu.train.business.mapper: trace
spring:
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      cache-null-values: true
      time-to-live: 10s
  application:
    name: business

  datasource:
    url: jdbc:mysql:///train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_business
    password: qweASDzx11_
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5   # 最小空闲连接数量
      idle-timeout: 180000   #  空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 20 # 连接池最大连接数，默认是10
      auto-commit: true # 控制从池返回的链接的默认自动提交行为，默认值：true
      pool-name: Hikari # 连接池名称
      max-lifetime: 1800000 # 控制池中链接的最长生命周期，值0表示无限生命周期，默认1800000，即30分钟
      connection-timeout: 30000 # 数据库链接超时时间，默认30秒，即30000
      connection-test-query: SELECT 1