package com.heyu.train.member.domain;

/**
 * 会员（表：member）
 *
 * @author heyu
 * @date 2024-03-23 13:49:55
 */
public class Member {
    /**
     * id
     */
    private Long id;

    /**
     * 手机号
     */
    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Sat Mar 23 13:49:55 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Sat Mar 23 13:49:55 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mobile
     *
     * @return the value of member.mobile
     *
     * @mbg.generated Sat Mar 23 13:49:55 CST 2024
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mobile
     *
     * @param mobile the value for member.mobile
     *
     * @mbg.generated Sat Mar 23 13:49:55 CST 2024
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}