package com.heyu.train.member.domain;

import java.util.Date;

/**
 * 乘车人（表：passenger）
 *
 * @author heyu
 * @date 2024-04-10 20:25:28
 */
public class Passenger {
    /**
     * id
     */
    private Long id;

    /**
     * 会员id
     */
    private Long memberId;

    /**
     * 姓名
     */
    private String name;

    /**
     * 身份证
     */
    private String idCard;

    /**
     * 旅客类型|枚举[PassengerTypeEnum]
     */
    private String type;

    /**
     * 新增时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.id
     *
     * @return the value of passenger.id
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.id
     *
     * @param id the value for passenger.id
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.member_id
     *
     * @return the value of passenger.member_id
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.member_id
     *
     * @param memberId the value for passenger.member_id
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.name
     *
     * @return the value of passenger.name
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.name
     *
     * @param name the value for passenger.name
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.id_card
     *
     * @return the value of passenger.id_card
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.id_card
     *
     * @param idCard the value for passenger.id_card
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.type
     *
     * @return the value of passenger.type
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.type
     *
     * @param type the value for passenger.type
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.create_time
     *
     * @return the value of passenger.create_time
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.create_time
     *
     * @param createTime the value for passenger.create_time
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.update_time
     *
     * @return the value of passenger.update_time
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.update_time
     *
     * @param updateTime the value for passenger.update_time
     *
     * @mbg.generated Wed Apr 10 20:25:28 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}