package com.heyu.train.member.domain;

import java.util.Date;

/**
 * （表：ticket）
 *
 * @author heyu
 * @date 2024-06-22 13:54:44
 */
public class Ticket {
    /**
     * 车票id
     */
    private Long id;

    /**
     * 会员id
     */
    private Long memberId;

    /**
     * 乘客id
     */
    private Long passengerId;

    /**
     * 乘客姓名
     */
    private String passengerName;

    /**
     * 日期
     */
    private Date date;

    /**
     * 车次编号
     */
    private String trainCode;

    /**
     * 排号
     */
    private String row;

    /**
     * 列号
     */
    private String col;

    /**
     * 座位类型
     */
    private String seatType;

    /**
     * 出发站
     */
    private String start;

    /**
     * 到达站
     */
    private String end;

    /**
     * 出发时间
     */
    private Date startTime;

    /**
     * 到达时间
     */
    private Date endTime;

    /**
     * 车厢号
     */
    private Integer carriageIndex;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 新增时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.id
     *
     * @return the value of ticket.id
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.id
     *
     * @param id the value for ticket.id
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.member_id
     *
     * @return the value of ticket.member_id
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.member_id
     *
     * @param memberId the value for ticket.member_id
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.passenger_id
     *
     * @return the value of ticket.passenger_id
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public Long getPassengerId() {
        return passengerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.passenger_id
     *
     * @param passengerId the value for ticket.passenger_id
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setPassengerId(Long passengerId) {
        this.passengerId = passengerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.passenger_name
     *
     * @return the value of ticket.passenger_name
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public String getPassengerName() {
        return passengerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.passenger_name
     *
     * @param passengerName the value for ticket.passenger_name
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.date
     *
     * @return the value of ticket.date
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.date
     *
     * @param date the value for ticket.date
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.train_code
     *
     * @return the value of ticket.train_code
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.train_code
     *
     * @param trainCode the value for ticket.train_code
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.row
     *
     * @return the value of ticket.row
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public String getRow() {
        return row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.row
     *
     * @param row the value for ticket.row
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setRow(String row) {
        this.row = row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.col
     *
     * @return the value of ticket.col
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public String getCol() {
        return col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.col
     *
     * @param col the value for ticket.col
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setCol(String col) {
        this.col = col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.seat_type
     *
     * @return the value of ticket.seat_type
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public String getSeatType() {
        return seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.seat_type
     *
     * @param seatType the value for ticket.seat_type
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setSeatType(String seatType) {
        this.seatType = seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.start
     *
     * @return the value of ticket.start
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.start
     *
     * @param start the value for ticket.start
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setStart(String start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.end
     *
     * @return the value of ticket.end
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.end
     *
     * @param end the value for ticket.end
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setEnd(String end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.start_time
     *
     * @return the value of ticket.start_time
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.start_time
     *
     * @param startTime the value for ticket.start_time
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.end_time
     *
     * @return the value of ticket.end_time
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.end_time
     *
     * @param endTime the value for ticket.end_time
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.carriage_index
     *
     * @return the value of ticket.carriage_index
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public Integer getCarriageIndex() {
        return carriageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.carriage_index
     *
     * @param carriageIndex the value for ticket.carriage_index
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setCarriageIndex(Integer carriageIndex) {
        this.carriageIndex = carriageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.create_time
     *
     * @return the value of ticket.create_time
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.create_time
     *
     * @param createTime the value for ticket.create_time
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.update_time
     *
     * @return the value of ticket.update_time
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.update_time
     *
     * @param updateTime the value for ticket.update_time
     *
     * @mbg.generated Sat Jun 22 13:54:44 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}