package com.heyu.train.business.domain;

import java.util.Date;

/**
 * 确认订单（表：confirm_order）
 *
 * @author heyu
 * @date 2024-06-06 19:00:21
 */
public class ConfirmOrder {
    /**
     * id
     */
    private Long id;

    /**
     * 会员id
     */
    private Long memberId;

    /**
     * 日期
     */
    private Date date;
    /**
     * 车次编号
     */
    private String trainCode;

    /**
     * 出发站
     */
    private String start;

    /**
     * 到达站
     */
    private String end;

    /**
     * 余票ID
     */
    private Long dailyTrainTicketId;

    /**
     * 订单状态|枚举[ConfirmOrderStatusEnum]
     */
    private String status;

    /**
     * 新增时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 车票
     */
    private String tickets;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.id
     *
     * @return the value of confirm_order.id
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.id
     *
     * @param id the value for confirm_order.id
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.member_id
     *
     * @return the value of confirm_order.member_id
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.member_id
     *
     * @param memberId the value for confirm_order.member_id
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.date
     *
     * @return the value of confirm_order.date
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.date
     *
     * @param date the value for confirm_order.date
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.train_code
     *
     * @return the value of confirm_order.train_code
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.train_code
     *
     * @param trainCode the value for confirm_order.train_code
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.start
     *
     * @return the value of confirm_order.start
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.start
     *
     * @param start the value for confirm_order.start
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setStart(String start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.end
     *
     * @return the value of confirm_order.end
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.end
     *
     * @param end the value for confirm_order.end
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setEnd(String end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.daily_train_ticket_id
     *
     * @return the value of confirm_order.daily_train_ticket_id
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public Long getDailyTrainTicketId() {
        return dailyTrainTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.daily_train_ticket_id
     *
     * @param dailyTrainTicketId the value for confirm_order.daily_train_ticket_id
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setDailyTrainTicketId(Long dailyTrainTicketId) {
        this.dailyTrainTicketId = dailyTrainTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.status
     *
     * @return the value of confirm_order.status
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.status
     *
     * @param status the value for confirm_order.status
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.create_time
     *
     * @return the value of confirm_order.create_time
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.create_time
     *
     * @param createTime the value for confirm_order.create_time
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.update_time
     *
     * @return the value of confirm_order.update_time
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.update_time
     *
     * @param updateTime the value for confirm_order.update_time
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confirm_order.tickets
     *
     * @return the value of confirm_order.tickets
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public String getTickets() {
        return tickets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confirm_order.tickets
     *
     * @param tickets the value for confirm_order.tickets
     *
     * @mbg.generated Thu Jun 06 19:00:21 CST 2024
     */
    public void setTickets(String tickets) {
        this.tickets = tickets;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}