package com.heyu.train.business.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 余票信息（表：daily_train_ticket）
 *
 * @author heyu
 * @date 2024-05-15 11:32:11
 */
public class DailyTrainTicket {
    /**
     * id
     */
    private Long id;

    /**
     * 日期
     */
    private Date date;

    /**
     * 车次编号
     */
    private String trainCode;
    /**
     * 出发站
     */
    private String start;

    /**
     * 出发站拼音
     */
    private String startPinyin;

    /**
     * 出发时间
     */
    private Date startTime;

    /**
     * 出发站序|本站是整个车次的第几站
     */
    private Integer startIndex;

    /**
     * 到达站
     */
    private String end;

    /**
     * 到达站拼音
     */
    private String endPinyin;

    /**
     * 到站时间
     */
    private Date endTime;

    /**
     * 到站站序|本站是整个车次的第几站
     */
    private Integer endIndex;

    /**
     * 一等座余票
     */
    private Integer ydz;

    /**
     * 一等座票价
     */
    private BigDecimal ydzPrice;

    /**
     * 二等座余票
     */
    private Integer edz;

    /**
     * 二等座票价
     */
    private BigDecimal edzPrice;

    /**
     * 软卧余票
     */
    private Integer rw;

    /**
     * 软卧票价
     */
    private BigDecimal rwPrice;

    /**
     * 硬卧余票
     */
    private Integer yw;

    /**
     * 硬卧票价
     */
    private BigDecimal ywPrice;

    /**
     * 新增时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.id
     *
     * @return the value of daily_train_ticket.id
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.id
     *
     * @param id the value for daily_train_ticket.id
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.date
     *
     * @return the value of daily_train_ticket.date
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.date
     *
     * @param date the value for daily_train_ticket.date
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.train_code
     *
     * @return the value of daily_train_ticket.train_code
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.train_code
     *
     * @param trainCode the value for daily_train_ticket.train_code
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.start
     *
     * @return the value of daily_train_ticket.start
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.start
     *
     * @param start the value for daily_train_ticket.start
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setStart(String start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.start_pinyin
     *
     * @return the value of daily_train_ticket.start_pinyin
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public String getStartPinyin() {
        return startPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.start_pinyin
     *
     * @param startPinyin the value for daily_train_ticket.start_pinyin
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setStartPinyin(String startPinyin) {
        this.startPinyin = startPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.start_time
     *
     * @return the value of daily_train_ticket.start_time
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Date getStartTime() {
        return startTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.start_time
     *
     * @param startTime the value for daily_train_ticket.start_time
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.start_index
     *
     * @return the value of daily_train_ticket.start_index
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Integer getStartIndex() {
        return startIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.start_index
     *
     * @param startIndex the value for daily_train_ticket.start_index
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setStartIndex(Integer startIndex) {
        this.startIndex = startIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.end
     *
     * @return the value of daily_train_ticket.end
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.end
     *
     * @param end the value for daily_train_ticket.end
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setEnd(String end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.end_pinyin
     *
     * @return the value of daily_train_ticket.end_pinyin
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public String getEndPinyin() {
        return endPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.end_pinyin
     *
     * @param endPinyin the value for daily_train_ticket.end_pinyin
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setEndPinyin(String endPinyin) {
        this.endPinyin = endPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.end_time
     *
     * @return the value of daily_train_ticket.end_time
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.end_time
     *
     * @param endTime the value for daily_train_ticket.end_time
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.end_index
     *
     * @return the value of daily_train_ticket.end_index
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Integer getEndIndex() {
        return endIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.end_index
     *
     * @param endIndex the value for daily_train_ticket.end_index
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setEndIndex(Integer endIndex) {
        this.endIndex = endIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.ydz
     *
     * @return the value of daily_train_ticket.ydz
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Integer getYdz() {
        return ydz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.ydz
     *
     * @param ydz the value for daily_train_ticket.ydz
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setYdz(Integer ydz) {
        this.ydz = ydz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.ydz_price
     *
     * @return the value of daily_train_ticket.ydz_price
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public BigDecimal getYdzPrice() {
        return ydzPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.ydz_price
     *
     * @param ydzPrice the value for daily_train_ticket.ydz_price
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setYdzPrice(BigDecimal ydzPrice) {
        this.ydzPrice = ydzPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.edz
     *
     * @return the value of daily_train_ticket.edz
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Integer getEdz() {
        return edz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.edz
     *
     * @param edz the value for daily_train_ticket.edz
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setEdz(Integer edz) {
        this.edz = edz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.edz_price
     *
     * @return the value of daily_train_ticket.edz_price
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public BigDecimal getEdzPrice() {
        return edzPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.edz_price
     *
     * @param edzPrice the value for daily_train_ticket.edz_price
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setEdzPrice(BigDecimal edzPrice) {
        this.edzPrice = edzPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.rw
     *
     * @return the value of daily_train_ticket.rw
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Integer getRw() {
        return rw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.rw
     *
     * @param rw the value for daily_train_ticket.rw
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setRw(Integer rw) {
        this.rw = rw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.rw_price
     *
     * @return the value of daily_train_ticket.rw_price
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public BigDecimal getRwPrice() {
        return rwPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.rw_price
     *
     * @param rwPrice the value for daily_train_ticket.rw_price
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setRwPrice(BigDecimal rwPrice) {
        this.rwPrice = rwPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.yw
     *
     * @return the value of daily_train_ticket.yw
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Integer getYw() {
        return yw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.yw
     *
     * @param yw the value for daily_train_ticket.yw
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setYw(Integer yw) {
        this.yw = yw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.yw_price
     *
     * @return the value of daily_train_ticket.yw_price
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public BigDecimal getYwPrice() {
        return ywPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.yw_price
     *
     * @param ywPrice the value for daily_train_ticket.yw_price
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setYwPrice(BigDecimal ywPrice) {
        this.ywPrice = ywPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.create_time
     *
     * @return the value of daily_train_ticket.create_time
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.create_time
     *
     * @param createTime the value for daily_train_ticket.create_time
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_ticket.update_time
     *
     * @return the value of daily_train_ticket.update_time
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_ticket.update_time
     *
     * @param updateTime the value for daily_train_ticket.update_time
     *
     * @mbg.generated Wed May 15 11:32:11 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}