package com.heyu.train.business.domain;

import java.util.Date;

/**
 * 每日车厢（表：daily_train_carriage）
 *
 * @author heyu
 * @date 2024-05-10 00:57:12
 */
public class DailyTrainCarriage {
    /**
     * id
     */
    private Long id;

    /**
     * 日期
     */
    private Date date;

    /**
     * 车次编号
     */
    private String trainCode;

    /**
     * 箱序
     */
    private Integer index;

    /**
     * 座位类型|枚举[SeatTypeEnum]
     */
    private String seatType;

    /**
     * 座位数
     */
    private Integer seatCount;

    /**
     * 排数
     */
    private Integer rowCount;

    /**
     * 列数
     */
    private Integer colCount;

    /**
     * 新增时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_carriage.id
     *
     * @return the value of daily_train_carriage.id
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_carriage.id
     *
     * @param id the value for daily_train_carriage.id
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_carriage.date
     *
     * @return the value of daily_train_carriage.date
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_carriage.date
     *
     * @param date the value for daily_train_carriage.date
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_carriage.train_code
     *
     * @return the value of daily_train_carriage.train_code
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_carriage.train_code
     *
     * @param trainCode the value for daily_train_carriage.train_code
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_carriage.index
     *
     * @return the value of daily_train_carriage.index
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_carriage.index
     *
     * @param index the value for daily_train_carriage.index
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_carriage.seat_type
     *
     * @return the value of daily_train_carriage.seat_type
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public String getSeatType() {
        return seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_carriage.seat_type
     *
     * @param seatType the value for daily_train_carriage.seat_type
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setSeatType(String seatType) {
        this.seatType = seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_carriage.seat_count
     *
     * @return the value of daily_train_carriage.seat_count
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Integer getSeatCount() {
        return seatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_carriage.seat_count
     *
     * @param seatCount the value for daily_train_carriage.seat_count
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setSeatCount(Integer seatCount) {
        this.seatCount = seatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_carriage.row_count
     *
     * @return the value of daily_train_carriage.row_count
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Integer getRowCount() {
        return rowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_carriage.row_count
     *
     * @param rowCount the value for daily_train_carriage.row_count
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setRowCount(Integer rowCount) {
        this.rowCount = rowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_carriage.col_count
     *
     * @return the value of daily_train_carriage.col_count
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Integer getColCount() {
        return colCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_carriage.col_count
     *
     * @param colCount the value for daily_train_carriage.col_count
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setColCount(Integer colCount) {
        this.colCount = colCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_carriage.create_time
     *
     * @return the value of daily_train_carriage.create_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_carriage.create_time
     *
     * @param createTime the value for daily_train_carriage.create_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_carriage.update_time
     *
     * @return the value of daily_train_carriage.update_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_carriage.update_time
     *
     * @param updateTime the value for daily_train_carriage.update_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}