package com.heyu.train.business.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 每日车站（表：daily_train_station）
 *
 * @author heyu
 * @date 2024-05-10 00:57:12
 */
public class DailyTrainStation {
    /**
     * id
     */
    private Long id;

    /**
     * 日期
     */
    private Date date;

    /**
     * 车次编号
     */
    private String trainCode;

    /**
     * 站序
     */
    private Integer index;

    /**
     * 站名
     */
    private String name;

    /**
     * 站名拼音
     */
    private String namePinyin;

    /**
     * 进站时间
     */
    private Date inTime;

    /**
     * 出站时间
     */
    private Date outTime;

    /**
     * 停站时长
     */
    private Date stopTime;

    /**
     * 里程（公里）|从上一站到本站的距离
     */
    private BigDecimal km;

    /**
     * 新增时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.id
     *
     * @return the value of daily_train_station.id
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.id
     *
     * @param id the value for daily_train_station.id
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.date
     *
     * @return the value of daily_train_station.date
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.date
     *
     * @param date the value for daily_train_station.date
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.train_code
     *
     * @return the value of daily_train_station.train_code
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.train_code
     *
     * @param trainCode the value for daily_train_station.train_code
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.index
     *
     * @return the value of daily_train_station.index
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.index
     *
     * @param index the value for daily_train_station.index
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.name
     *
     * @return the value of daily_train_station.name
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.name
     *
     * @param name the value for daily_train_station.name
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.name_pinyin
     *
     * @return the value of daily_train_station.name_pinyin
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public String getNamePinyin() {
        return namePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.name_pinyin
     *
     * @param namePinyin the value for daily_train_station.name_pinyin
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setNamePinyin(String namePinyin) {
        this.namePinyin = namePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.in_time
     *
     * @return the value of daily_train_station.in_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.in_time
     *
     * @param inTime the value for daily_train_station.in_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.out_time
     *
     * @return the value of daily_train_station.out_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.out_time
     *
     * @param outTime the value for daily_train_station.out_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.stop_time
     *
     * @return the value of daily_train_station.stop_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.stop_time
     *
     * @param stopTime the value for daily_train_station.stop_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setStopTime(Date stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.km
     *
     * @return the value of daily_train_station.km
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public BigDecimal getKm() {
        return km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.km
     *
     * @param km the value for daily_train_station.km
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setKm(BigDecimal km) {
        this.km = km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.create_time
     *
     * @return the value of daily_train_station.create_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.create_time
     *
     * @param createTime the value for daily_train_station.create_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.update_time
     *
     * @return the value of daily_train_station.update_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.update_time
     *
     * @param updateTime the value for daily_train_station.update_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}