package com.heyu.train.business.domain;

import java.util.Date;

/**
 * 每日座位（表：daily_train_seat）
 *
 * @author heyu
 * @date 2024-05-10 00:57:12
 */
public class DailyTrainSeat {
    /**
     * id
     */
    private Long id;

    /**
     * 日期
     */
    private Date date;

    /**
     * 车次编号
     */
    private String trainCode;

    /**
     * 箱序
     */
    private Integer carriageIndex;

    /**
     * 排号|01, 02
     */
    private String row;

    /**
     * 列号|枚举[SeatColEnum]
     */
    private String col;

    /**
     * 座位类型|枚举[SeatTypeEnum]
     */
    private String seatType;

    /**
     * 同车箱座序
     */
    private Integer carriageSeatIndex;

    /**
     * 售卖情况|将经过的车站用01拼接，0表示可卖，1表示已卖
     */
    private String sell;

    /**
     * 新增时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.id
     *
     * @return the value of daily_train_seat.id
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.id
     *
     * @param id the value for daily_train_seat.id
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.date
     *
     * @return the value of daily_train_seat.date
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.date
     *
     * @param date the value for daily_train_seat.date
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.train_code
     *
     * @return the value of daily_train_seat.train_code
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.train_code
     *
     * @param trainCode the value for daily_train_seat.train_code
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.carriage_index
     *
     * @return the value of daily_train_seat.carriage_index
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Integer getCarriageIndex() {
        return carriageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.carriage_index
     *
     * @param carriageIndex the value for daily_train_seat.carriage_index
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setCarriageIndex(Integer carriageIndex) {
        this.carriageIndex = carriageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.row
     *
     * @return the value of daily_train_seat.row
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public String getRow() {
        return row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.row
     *
     * @param row the value for daily_train_seat.row
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setRow(String row) {
        this.row = row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.col
     *
     * @return the value of daily_train_seat.col
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public String getCol() {
        return col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.col
     *
     * @param col the value for daily_train_seat.col
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setCol(String col) {
        this.col = col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.seat_type
     *
     * @return the value of daily_train_seat.seat_type
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public String getSeatType() {
        return seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.seat_type
     *
     * @param seatType the value for daily_train_seat.seat_type
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setSeatType(String seatType) {
        this.seatType = seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.carriage_seat_index
     *
     * @return the value of daily_train_seat.carriage_seat_index
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Integer getCarriageSeatIndex() {
        return carriageSeatIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.carriage_seat_index
     *
     * @param carriageSeatIndex the value for daily_train_seat.carriage_seat_index
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setCarriageSeatIndex(Integer carriageSeatIndex) {
        this.carriageSeatIndex = carriageSeatIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.sell
     *
     * @return the value of daily_train_seat.sell
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public String getSell() {
        return sell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.sell
     *
     * @param sell the value for daily_train_seat.sell
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setSell(String sell) {
        this.sell = sell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.create_time
     *
     * @return the value of daily_train_seat.create_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.create_time
     *
     * @param createTime the value for daily_train_seat.create_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_seat.update_time
     *
     * @return the value of daily_train_seat.update_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_seat.update_time
     *
     * @param updateTime the value for daily_train_seat.update_time
     *
     * @mbg.generated Fri May 10 00:57:12 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}