package com.heyu.train.business.domain;

import java.util.Date;

/**
 * 车站（表：station）
 *
 * @author heyu
 * @date 2024-04-15 11:57:28
 */
public class Station {
    /**
     * id
     */
    private Long id;

    /**
     * 站名
     */
    private String name;

    /**
     * 站名拼音
     */
    private String namePinyin;

    /**
     * 站名拼音首字母
     */
    private String namePy;

    /**
     * 新增时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.id
     *
     * @return the value of station.id
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.id
     *
     * @param id the value for station.id
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.name
     *
     * @return the value of station.name
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.name
     *
     * @param name the value for station.name
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.name_pinyin
     *
     * @return the value of station.name_pinyin
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public String getNamePinyin() {
        return namePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.name_pinyin
     *
     * @param namePinyin the value for station.name_pinyin
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public void setNamePinyin(String namePinyin) {
        this.namePinyin = namePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.name_py
     *
     * @return the value of station.name_py
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public String getNamePy() {
        return namePy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.name_py
     *
     * @param namePy the value for station.name_py
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public void setNamePy(String namePy) {
        this.namePy = namePy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.create_time
     *
     * @return the value of station.create_time
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.create_time
     *
     * @param createTime the value for station.create_time
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.update_time
     *
     * @return the value of station.update_time
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.update_time
     *
     * @param updateTime the value for station.update_time
     *
     * @mbg.generated Mon Apr 15 11:57:28 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}