package com.heyu.train.business.domain;

import java.util.Date;

/**
 * 车次（表：train）
 *
 * @author heyu
 * @date 2024-04-16 00:05:23
 */
public class Train {
    /**
     * id
     */
    private Long id;

    /**
     * 车次编号
     */
    private String code;

    /**
     * 车次类型|枚举[TrainTypeEnum]
     */
    private String type;

    /**
     * 始发站
     */
    private String start;

    /**
     * 始发站拼音
     */
    private String startPinyin;

    /**
     * 出发时间
     */
    private Date startTime;

    /**
     * 终点站
     */
    private String end;

    /**
     * 终点站拼音
     */
    private String endPinyin;

    /**
     * 到站时间
     */
    private Date endTime;

    /**
     * 新增时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.id
     *
     * @return the value of train.id
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.id
     *
     * @param id the value for train.id
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.code
     *
     * @return the value of train.code
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.code
     *
     * @param code the value for train.code
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.type
     *
     * @return the value of train.type
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.type
     *
     * @param type the value for train.type
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.start
     *
     * @return the value of train.start
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.start
     *
     * @param start the value for train.start
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setStart(String start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.start_pinyin
     *
     * @return the value of train.start_pinyin
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public String getStartPinyin() {
        return startPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.start_pinyin
     *
     * @param startPinyin the value for train.start_pinyin
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setStartPinyin(String startPinyin) {
        this.startPinyin = startPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.start_time
     *
     * @return the value of train.start_time
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.start_time
     *
     * @param startTime the value for train.start_time
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.end
     *
     * @return the value of train.end
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.end
     *
     * @param end the value for train.end
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setEnd(String end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.end_pinyin
     *
     * @return the value of train.end_pinyin
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public String getEndPinyin() {
        return endPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.end_pinyin
     *
     * @param endPinyin the value for train.end_pinyin
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setEndPinyin(String endPinyin) {
        this.endPinyin = endPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.end_time
     *
     * @return the value of train.end_time
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.end_time
     *
     * @param endTime the value for train.end_time
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.create_time
     *
     * @return the value of train.create_time
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.create_time
     *
     * @param createTime the value for train.create_time
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.update_time
     *
     * @return the value of train.update_time
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.update_time
     *
     * @param updateTime the value for train.update_time
     *
     * @mbg.generated Tue Apr 16 00:05:23 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}