package com.heyu.train.business.domain;

import java.util.Date;

/**
 * 座位（表：train_seat）
 *
 * @author heyu
 * @date 2024-04-23 23:43:44
 */
public class TrainSeat {
    /**
     * id
     */
    private Long id;

    /**
     * 车次编号
     */
    private String trainCode;

    /**
     * 厢序
     */
    private Integer carriageIndex;

    /**
     * 排号|01, 02
     */
    private String row;

    /**
     * 列号|枚举[SeatColEnum]
     */
    private String col;

    /**
     * 座位类型|枚举[SeatTypeEnum]
     */
    private String seatType;

    /**
     * 同车厢座序
     */
    private Integer carriageSeatIndex;

    /**
     * 新增时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.id
     *
     * @return the value of train_seat.id
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.id
     *
     * @param id the value for train_seat.id
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.train_code
     *
     * @return the value of train_seat.train_code
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.train_code
     *
     * @param trainCode the value for train_seat.train_code
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.carriage_index
     *
     * @return the value of train_seat.carriage_index
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public Integer getCarriageIndex() {
        return carriageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.carriage_index
     *
     * @param carriageIndex the value for train_seat.carriage_index
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public void setCarriageIndex(Integer carriageIndex) {
        this.carriageIndex = carriageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.row
     *
     * @return the value of train_seat.row
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public String getRow() {
        return row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.row
     *
     * @param row the value for train_seat.row
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public void setRow(String row) {
        this.row = row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.col
     *
     * @return the value of train_seat.col
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public String getCol() {
        return col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.col
     *
     * @param col the value for train_seat.col
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public void setCol(String col) {
        this.col = col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.seat_type
     *
     * @return the value of train_seat.seat_type
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public String getSeatType() {
        return seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.seat_type
     *
     * @param seatType the value for train_seat.seat_type
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public void setSeatType(String seatType) {
        this.seatType = seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.carriage_seat_index
     *
     * @return the value of train_seat.carriage_seat_index
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public Integer getCarriageSeatIndex() {
        return carriageSeatIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.carriage_seat_index
     *
     * @param carriageSeatIndex the value for train_seat.carriage_seat_index
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public void setCarriageSeatIndex(Integer carriageSeatIndex) {
        this.carriageSeatIndex = carriageSeatIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.create_time
     *
     * @return the value of train_seat.create_time
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.create_time
     *
     * @param createTime the value for train_seat.create_time
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.update_time
     *
     * @return the value of train_seat.update_time
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.update_time
     *
     * @param updateTime the value for train_seat.update_time
     *
     * @mbg.generated Tue Apr 23 23:43:44 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
        if (this.getRow() == null) {
            this.setRow("0");
        }
    }

    public void initUpdate() {
    }
}